backbone: se_resnext50_32x4d
exp_name: original_224_filter_ar
description: 
data_folder: /data/lxd/datasets/2022-04-18-Eggs
training_set: train.csv
test_set: test.csv
test_real_world_set: seed
test_real_world_num: 10
num_classes: 5
lr: 0.001
train_transforms: a2
train_batch_size: 96
fold_i: 0
val_batch_size: 96
anchor_batch_size: 6
save_top_k: 6
training_mode: ddp
num_workers: 8
image_size: [264, 224]
seed: 2022
min_epochs: 10
max_epochs: 70
patience: 10
gpus: [2, 3]
precision: 16
gradient_clip_val: 0
soft_labels_filename: ''
log_dir: logs_submit
sample_num: 6
debug: false
clean_debug: true
norm:
  mean: [0, 0, 0]
  std: [1, 1, 1]
skip_folds: []
resume_from_checkpoint: 
checkpoints: null
test_batch_size: 96
train_num_workers: 8
val_num_workers: 0
test_num_workers: 8
metrics: mAP
eval_mode: train
data_mask: /data/lxd/datasets/2022-04-18-Egg-Masks
model_type: base
dataset: base
classes: ['OK', 'AirRoomShake', 'Dead', 'Empty', 'NoAirRoom', 'Split', 'Weak','Flower']
filter_classes: ['AirRoomShake']
# filter_classes: []
