backbone: se_resnext50_32x4d
exp_name: original_224_mask2
description: original
data_folder: /data/lxd/datasets/2022-04-18-Eggs
data_mask: /data/lxd/datasets/2022-04-18-Egg-Masks
training_set: train.csv
test_set: test.csv
num_classes: 8
lr: 0.001
train_transforms: a2
train_batch_size: 96
fold_i: 0
val_batch_size: 128
anchor_batch_size: 6
training_mode: ddp
eval_mode: train
num_workers: 8
image_size: [264, 224]
seed: 2022
min_epochs: 10
max_epochs: 70
gpus: [0, 1]
precision: 16
gradient_clip_val: 0
soft_labels_filename: ''
log_dir: logs_submit
sample_num: 6
debug: false
norm:
  mean: [0, 0, 0]
  std: [1, 1, 1]
resume_from_checkpoint: null
checkpoints: null
test_real_world_set: seed
test_real_world_num: 10
save_top_k: 5
patience: 10
clean_debug: false
skip_folds: []
test_batch_size: 128
train_num_workers: 8
val_num_workers: 8
test_num_workers: 8
metrics: mAP
model_type: mask2
dataset: mask
classes: [OK, AirRoomShake, Dead, Empty, NoAirRoom, Split, Weak, Flower]
filter_classes: []
loss: 'cross_entropy_loss'